version: '3.8'
services:
  nba-backend:
    image: jayakrishnansharangan/nba-backend:latest
    ports:
      - "8000:8000"
    restart: always

  nba-frontend:
    image: jayakrishnansharangan/nba-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/predict
    restart: always
