version: '3.8'
services:
  nba-backend:
    image: jayakrishnansharangan/nba-backend:latest
    ports:
      - "8080:8000"
    restart: always

  nba-frontend:
    image: jayakrishnansharangan/nba-frontend:latest
    ports:
      - "30000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://AWS_TARGET_IP:8080/predict
    restart: always
