apiVersion: apps/v1
kind: Deployment
metadata:
  name: nba-frontend
  labels:
    app: nba-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nba-frontend
  template:
    metadata:
      labels:
        app: nba-frontend
    spec:
      containers:
        - name: frontend
          image: docker.io/jayakrishnansharangan/nba-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://98.93.213.189:31019/predict"
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nba-frontend-service
spec:
  type: NodePort
  selector:
    app: nba-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30000
